### ISSUE TITLE
Can't run the p1 path

### ISSUE THREAD

**Issue by SamehHanna** [davidtucker/ps-serverless-app#16]
I am not sure if anyone else faced this problem but after importing p1 and using yarn to install all dependencies. I ran "yarn start" from the webapp folder and it gave me the next error in the browser.  Could you please help? @davidtucker 

TypeError: Cannot read properties of undefined (reading 'apiEndpoint')
Module.<anonymous>
F:/ServerLess/ps-serverless-app-p1/ps-serverless-app/webapp/src/services/index.js:5
  2 | import createAuthRefreshInterceptor from 'axios-auth-refresh';
  3 | import { Auth } from 'aws-amplify';
  4 | 
> 5 | const SERVICES_HOST = window.appConfig.apiEndpoint;
  6 | let client;
  7 | 
  8 | /* eslint-disable no-console */

**Comment by davidtucker** [comment]
Please check your branch. The code that you mention here is not in the `p1` branch.  I suspect that you may still be on the `main` branch.  If you are still having trouble, please reopen and let me know.
