### ISSUE TITLE
fail: Inaccessible host: `cdk-hnb659fds-assets-XXXXX-us-east-1.s3.amazonaws.com'

### ISSUE THREAD

**Issue by gc-it** [davidtucker/ps-serverless-app#2]
Hello @davidtucker ,
First of all this is a good course and a starting point for CDK / Pipeline etc.
I have tried to setup the project and run it in AWS and noticed that I'm getting below error for some zip file uploads:

fail: Inaccessible host: `cdk-hnb659fds-assets-xxxxx-us-east-1.s3.amazonaws.com'. This service may not be available in the `us-east-1' region.

So my ApplicationStack / PipelinStack are failing to complete deployment..

I was able to successfully upload some assets and some are failing, any advise is much appreciated.

Thanks
Chris

**Comment by rluisnpt1** [comment]
Hi, well, the best way to fix this issue is to make sure your that the arn of ghostscript that you are using is in the same region as your account and bucket. Here is the link with all arn created by the author of ghostscript 
https://github.com/shelfio/ghostscript-lambda-layer

**Comment by davidtucker** [comment]
@rluisnpt1 is correct here.  Make sure to use the regions that I specify in the course to avoid any issues like this when deploying.  Feel free to reopen if you are still experiencing any issue.
