### ISSUE TITLE
Suggestion: Check for required installed apps etc, issue newbie-friendly message

### ISSUE THREAD

**Issue by mike-whittaker-work** [davidtucker/ps-serverless-app#20]
The Pluralsight course is very clear, however it's possible to get so far then have problems with missing installed programs, but for which the error message is unclear and unhelpful in getting things sorted.

eg Error: spawnSync docker ENOENT

Might be useful to have a module that just checks that eg Docker etc is installed and tells you if not. A "pre-flight check".

**Comment by davidtucker** [comment]
I agree, and the CDK has addressed this recently by providing a more clear message when Docker cannot be spawned.
