### ISSUE TITLE
Suggestion/research: Security - "Prevent requests from accessing API directly"

### ISSUE THREAD

**Issue by mike-whittaker-work** [davidtucker/ps-serverless-app#23]
Summary: As a security hardening approach, it makes sense to deny "backdoor" requests to your API, unless coming from Cloudfront ...

Of course, switching this on will make Postman testing more difficult, so might be an idea to make it easily switchable.

Might post some code updates here, if it all works.

https://www.wellarchitectedlabs.com/security/300_labs/300_multilayered_api_security_with_cognito_and_waf/3_prevent_requests_from_accessing_api_directly/

**Comment by davidtucker** [comment]
Another great suggestion here.  I'll also consider this for an updated version of the course.
