### ISSUE TITLE
Suggestion/research: Security - Help manage security by adding response headers to CloudFront

### ISSUE THREAD

**Issue by mike-whittaker-work** [davidtucker/ps-serverless-app#24]
Summary: As a security hardening approach, add some security-oriented response headers to CloudFront

Might post some code updates here, if it all works.

https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-cloudfront-introduces-response-headers-policies/

**Comment by davidtucker** [comment]
I totally agree that this is a good thing to consider.  Unfortunately, I don't currently have a course in the learning path focused on security.  I'll keep this in a separate set of notes for consideration when I update the course (which I am working on now).
