### ISSUE TITLE
Unable to deploy - npx cdk deploy

### ISSUE THREAD

**Issue by srcsakthivel** [davidtucker/ps-serverless-app#26]
Resource handler returned message: "The runtime parameter of python3.6 is no longer supported for creating or updating AWS Lambda functions. We recommend you u
se the new runtime (python3.9) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 6e070690-e0a8-43eb-bb26-419bced59b2b)" (Re
questToken: 64b577d6-fa91-752c-9334-66f3f0a6bc5f, HandlerErrorCode: InvalidRequest)

**Comment by davidtucker** [comment]
Thank you for this heads up.  I'll review and get an update in place in the near future.

**Comment by andy-mc** [comment]
It will be wonderfull can deploy the code as in the videos I have the same error I think some library needs to be updated I try to make it work but with out success :c

**Comment by DavidFransch** [comment]
Please gives us an update on this issue or a possible work around.

**Comment by davidtucker** [comment]
All branches have been updated to CDK v. 1.178.0 which should resolve this issue.  Please re-open if you still have issues deploying.  Apologies for the delay on this.
