### ISSUE TITLE
npx cdk deploy error

### ISSUE THREAD

**Issue by t2dstudio** [davidtucker/ps-serverless-app#6]
Hello,
I am getting this error on p1 while trying to utilize @cdk-webapp-tools for cdk construct.

Bundling asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage...
docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
**Failed to bundle asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage, bundle output is located at C:\ReactApp\ps-serverless-app-**p1\infrastructure\cdk.out\asset.771d2d7f452140bc9bf28eafbc13fe5ced81f23acd2fbe17b238c1d840a5fb50-error: Error: docker exited with status 127
Subprocess exited with error 1

I guess i have to install the dependency but dont know how to do that

**Comment by rluisnpt1** [comment]
This error generally will occur if you do not have docker installed and running in you machine. Did you tried to install docker in your machine ?

**Comment by davidtucker** [comment]
As @rluisnpt1 mentioned, this is because Docker is not running.  Please let me know if Docker is running and you still experience this issue.

**Comment by abeel50** [comment]
> Hello, I am getting this error on p1 while trying to utilize @cdk-webapp-tools for cdk construct.
> 
> Bundling asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage... docker: error during connect: This error may indicate that the docker daemon is not running.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified. See 'docker run --help'. **Failed to bundle asset ApplicationStack/WebApp/WebAppDeploy/WebAppDeploy/Asset1/Stage, bundle output is located at C:\ReactApp\ps-serverless-app-**p1\infrastructure\cdk.out\asset.771d2d7f452140bc9bf28eafbc13fe5ced81f23acd2fbe17b238c1d840a5fb50-error: Error: docker exited with status 127 Subprocess exited with error 1
> 
> I guess i have to install the dependency but dont know how to do that


Facing same issue

**Comment by abeel50** [comment]
> As @rluisnpt1 mentioned, this is because Docker is not running. Please let me know if Docker is running and you still experience this issue.

thanks let me check.

**Comment by abeel50** [comment]
> As @rluisnpt1 mentioned, this is because Docker is not running. Please let me know if Docker is running and you still experience this issue.

Thanks @davidtucker got it.
Thanks
