### ISSUE TITLE
Eventbus and Cloudtrail

### ISSUE THREAD

**Issue by dragontuck** [davidtucker/ps-serverless-app#9]
With the code as is the event bus will not get events without setting up a CloudTrail to monitor the upload bucket.  Once CloudTrail is set up this is another issue, it adds a logs folder to the bucket. So every time a new log file is added the Step Function is triggered and fails.  Is there a way to filter the events to ignore the 'AWSLogs' folder?

**Comment by rluisnpt1** [comment]
Could you share how did you setting up CloudTrail?
